services:
  postgres:
    image: postgres:lastest
    container_name: BankProject
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5431:5432"
    restart: always